version: 2
updates:
- package-ecosystem: nuget
  directory: "/"
  schedule:
    interval: daily
    time: "03:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: YamlDotNet
    versions:
    - 10.0.0
    - 11.0.1
    - 11.1.0
    - 9.1.4
  - dependency-name: Handlebars.Net
    versions:
    - 2.0.4
    - 2.0.5
    - 2.0.6
